name: SCADE CICD DEMO
run-name: ${{ github.actor }} is playing SCADE CICD Demo 🚀
on:
  pull_request:
  push:
    tags:
      - "*"
    branches:
      - main
  workflow_dispatch:


env:
  MAIN_PYTHON_VERSION: '3.10'
  DOCUMENTATION_CNAME: 'Calculator'
  LIBRARY_NAME: 'Calculator'
  ARTIFACT_NAME: 'Calculator'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  build-project:
    name: "Build Project"
    runs-on: [self-hosted, 'xiao-laptop']
    strategy:
      matrix:
        os: [windows-latest]
        scade-version: ['24.2']
      fail-fast: false
    steps:
        - name: "Install Git and clone project"
          uses: actions/checkout@v4
        
        - name: "Get SCADE installation directory"
          uses: ansys/scade-actions/get-scade-dir@v2
          id: get-scade-dir
          with:
            scade-version: "24.2"
        
        - name: "Get the Python installation installed with Ansys SCADE"
          uses: ansys/scade-actions/get-scade-python@v2
          id: get-scade-python
          with:
            scade-dir: ${{ steps.get-scade-dir.outputs.scade-directory }}
